# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: 
      STAGING_EN: gs://locals-1/locales-staging/locales/en/
      STAGING_DE: gs://locals-1/locales-staging/locales/de/
      PRODUCTION: ""

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v27

      - name: Authenticate into GCP
        run: |
          echo "$GCP_SA_KEY" > ${HOME}/service-account-key.json
          gcloud auth activate-service-account --key-file=${HOME}/service-account-key.json --project=$GCP_PROJECT_ID
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      - name: Run step for all changed files and put into Github Env
        run: |
          configPaths=()

          for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
            if [[ ${file:0:7} = "config/" ]]; then
                configPaths+=(${file:7}})
            fi;
          done
          echo "configPaths=${configPaths[@]}" >> $GITHUB_ENV

      - name: Get all buckets that exist and put into Github ENV
        run: |
          gcpBuckets=$(gsutil ls ${{ env.STAGING_EN }} )
          echo "gcpBuckets=$gcpBuckets" >> $GITHUB_ENV

      - name: Loop through the GCP buckets, and see if any of the buckets match in name
        run: |
          for changedFile in $CONFIG_PATHS; do
            for bucketFile in $GCPBUCKETS; do
              fileInBucket=$( echo $bucketFile | rev | cut -d'/' -f1 | rev)
              if [[ changedFile == fileInBucket ]]; then
                gsutil cp changedFile "$STAGING_EN"/"changedFile"
              fi;
            done;
          done;
        env:
          CONFIG_PATHS: ${{ env.configPaths }}
          GCP_BUCKETS: ${{ env.gcpBuckets }}
